### ISSUE TITLE
missing training.py file ?

### ISSUE THREAD

**Issue by dseddah** [asofiaoliveira/srl_bert_pt#1]
Hi,
thanks for putting your code online :)
Would it be possible to include the training.py file in this repo ? I'd like to retrain your model on another language with SRL to see  how it goes.

Thanks in advance
Djamé

**Comment by asofiaoliveira** [comment]
Hi!
I'm assuming you're looking at the main branch. That is the code for using the models.
The code I used to run them is in the [branch v1.0.0rc3](https://github.com/asofiaoliveira/srl_bert_pt/tree/v1.0.0rc3). That branch has a file train.py 

Like I say in the README, 

> There are three branches in this repository, which correspond to three different versions of the AllenNLP package. The branch v1.0.0rc3 contains the code used to train the models reported in the article. The branch v1.0.0 contains the code used to test the models reported. The models were trained and tested in different versions because of a bug in version 1.0.0rc3 of AllenNLP which prevented testing some models. The main branch contains the code needed to make predictions with the trained models.

Let me know if this solves your problem

Sofia

**Comment by dseddah** [comment]
Thanks a lot of your reactivity :)
Sorry, I missed that mention about the branch. Thanks a lot :)

**Comment by asofiaoliveira** [comment]
No problem, happy to help :)
