### ISSUE TITLE
Parser class file

### ISSUE THREAD

**Issue by ArijRB** [asofiaoliveira/srl_bert_pt#2]
Hi,
Thank you for sharing your code.

I couldn't find the code for your model when you fine-tune on dependency parsing. I looked in the branch for the training. 
You used a biaffine parser on top of Bert-like architecture?
Thanks in advance.

**Comment by asofiaoliveira** [comment]
Hi 
I used the biaffine parsing model from allennlp_models with the BERT-like architecture as the text field embedder.

**Comment by ArijRB** [comment]
Thank you for your response.
