### ISSUE TITLE
Path of vocabulary in get_model is wrong

### ISSUE THREAD

**Issue by evelinamorim** [asofiaoliveira/srl_bert_pt#4]
In Line 16 and line 26, the directory is "Vocabulary", but in the Models directory there is no such directory. There is, however, "vocabulary". The first letter is lower and not capital

**Comment by asofiaoliveira** [comment]
Hello, thank you for reporting
I had some uppercase and some lowercase so I changed every folder to uppercase "Vocabulary"

Please feel free to reopen this issue if there are still problems
