### ISSUE TITLE
FileNotFoundError: file ud_srl-enpt_xlmr-large/vocabulary not found

### ISSUE THREAD

**Issue by alapanju** [asofiaoliveira/srl_bert_pt#5]
Thanks for sharing your work. 
Can you please help me here. I am getting this error while using your model:

FileNotFoundError: file ud_srl-enpt_xlmr-large/vocabulary not found

FileNotFoundError: file srl-pt_bertimbau-large/vocabulary not found

Please help me. I am stuck here. Thanks in advance!!

**Comment by asofiaoliveira** [comment]
Hi, thanks for reaching out! 
Could you please tell me what your operating system is, the versions of your `allennlp` and `allennlp-models` and what you ran to get those errors?
Also, please make sure you have the latest commit.

**Comment by asofiaoliveira** [comment]
Hello. I believe I found the error. Please download the new commits and test it again. 
If you still have an error, feel free to reopen this issue
